name: Enrolling.API

on:
  push:
    paths:
    - 'src/Services/Enrolling/**'
  pull_request:
    paths:
    - 'src/Services/Enrolling/**'

jobs:

  build:
 
    runs-on: ubuntu-16.04
 
    steps:
    - uses: actions/checkout@v1
    - name: docker compose
      run: docker-compose build enrolling.api
